In [1]:
# creating a basic 3d array using ndarray()
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9)])  # creates a 3rd array
print(a.ndim)

2


In [2]:
# calcualting speed 
import numpy as np
distance = [10, 20, 30, 40, 50]
time = [0.30, 0.40, 0.50, 0.60, 0.70]
qs , ts = np.array(distance) , np.array(time)
speed = qs/ts
speed

array([33.33333333, 50.        , 60.        , 66.66666667, 71.42857143])

INITIAL PLACEHOLDERS

In [27]:
# creating array with zeros
import numpy as np
c = np.zeros((3,3))
c.ndim

2

In [24]:
# creating array with ones
b = np.ones((3,3),dtype=int)
b.ndim

2

In [20]:
c = np.arange(10,25,5)
c

array([10, 15, 20])

In [30]:
a = np.array([[[1,2,3,4]]])
a

array([[[1, 2, 3, 4]]])