In [1]:
pip install scipy

     ---------------------------------------- 36.9/36.9 MB 7.8 MB/s eta 0:00:00


In [2]:
from scipy.integrate import quad

In [8]:
def integrateFunc(x):
    return x

In [9]:
quad(integrateFunc, 0, 1)

(0.5, 5.551115123125783e-15)

In [10]:
def integrateFn(x,a,b):
    return x*a+b

In [11]:
a = 3
b = 2

In [13]:
quad(integrateFn, 0, 1, args=(a,b))

(3.5, 3.885780586188048e-14)

## Double Integration

In [14]:
import scipy.integrate as integrate

In [15]:
def func(x, y):
    return x + y

In [16]:
integrate.dblquad(func, 0, 1, lambda x: 0, lambda x: 2)

(3.0, 4.436070580899685e-14)

## Optimization

In [17]:
import numpy as np
from scipy import optimize

In [21]:
def func(x):
    return x**2 + 5 * np.sin(x)

In [24]:
minimaValue = optimize.minimize(func, x0=2, method='bfgs', options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [25]:
minimaValueWithoutOptions = optimize.minimize(func, x0=2, method='bfgs')

In [26]:
minimaValueWithoutOptions

      fun: -3.2463942726915125
 hess_inv: array([[0.15445863]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051059])

In [27]:
from scipy.optimize import root

In [28]:
def rootFunc(x):
    return x + 3.5 * np.cos(x)

In [33]:
rootValue = root(rootFunc, 0.3)

In [34]:
rootValue

    fjac: array([[-1.]])
     fun: array([2.22044605e-16])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32223179e-13])
       r: array([-4.28198142])
  status: 1
 success: True
       x: array([-1.21597614])

## Inverse of Matrix

In [35]:
import numpy as np
from scipy import linalg

In [36]:
matrix = np.array([[11, 12], [21, 22]])
matrix

array([[11, 12],
       [21, 22]])

In [37]:
type(matrix)

numpy.ndarray

In [38]:
linalg.inv(matrix)

array([[-2.2,  1.2],
       [ 2.1, -1.1]])

## Determinant for a matrix

In [39]:
linalg.det(matrix)

-10.000000000000028

## Solving Linear Equations

In [40]:
# Given Equations
'''2x+3y+z = 21
   -x+5y+4z = 9
   3x+2y+9z = 6'''


numArray = np.array([[2,3,1], [-1,5,4], [3,2,9]])
numValues = np.array([21,9,6])

In [41]:
linalg.solve(numArray, numValues)

array([ 4.95,  4.35, -1.95])

## Single value decomposition

In [43]:
numSvdArr = np.array([[3,5,1], [9,5,7]])
numSvdArr.shape

(2, 3)

In [44]:
linalg.svd(numSvdArr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

## Eigen Values and Eigen Vectors

In [1]:
import numpy as np
from scipy import linalg

In [2]:
test_rating_data = np.array([[5, 8], [7, 9]])

In [3]:
eigenValues, eigenVector = linalg.eig(test_rating_data)

In [4]:
first_eigen, second_eigen = eigenValues

In [5]:
print(f"First eigen value => {first_eigen} === Second eigen value => {second_eigen}")

First eigen value => (-0.745966692414834+0j) === Second eigen value => (14.745966692414834+0j)


In [6]:
print(eigenVector[:, 0])

[-0.81220939  0.58336601]


In [7]:
print(eigenVector[:, 1])

[-0.63447346 -0.77294465]


## Statistics Package

In [8]:
from scipy.stats import norm

In [15]:
norm.rvs(loc=1, scale=1, size=10)

array([ 1.56275561,  1.14197304,  0.98861135, -0.21738147,  1.65424815,
        0.37040869,  1.40978894,  1.41579459,  1.72287262,  0.49671987])

In [16]:
norm.cdf(5, loc=1, scale=2)

0.9772498680518208

In [17]:
norm.pdf(9, loc=0, scale=1) 

1.0279773571668917e-18