In [1]:
import sys

In [2]:
print(sys.version)

3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]


In [3]:
import platform

In [4]:
platform.python_version()

'3.8.10'

# NUMPY

In [10]:
import numpy as np

In [21]:
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype = int)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
distance = [10, 20, 30, 40, 50]
time = [0.30, 0.40, 0.50, 0.60, 0.70]

In [4]:
np_distance = np.array(distance)
np_time = np.array(time)

In [5]:
speed = np_distance/np_time

In [6]:
speed

array([33.33333333, 50.        , 60.        , 66.66666667, 71.42857143])

In [9]:
first_numpy_array = np.array([1,2,3,4])

In [10]:
print(first_numpy_array)

[1 2 3 4]


In [ ]:
array_with_zeros = np.zeros((3,3))

In [12]:
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
array_with_ones = np.ones((4,4))
print(array_with_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
empty_array = np.empty((2,3))
print(empty_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
np_arange = np.arange(12) # To generate list in a given range
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
np_arange.reshape(4, 3) # To reshape an array.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np_linspace = np.linspace(1,6,5) # linspace for linearly (equal) spaced data elements
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [29]:
oneD_array = np.arange(15)

In [30]:
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [32]:
twoD_array = oneD_array.reshape(3, 5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [38]:
twoD_array.ndim # To find the dimension of the array

2

In [39]:
twoD_array.size # To find the number of elemnts in an array

15

In [40]:
twoD_array.dtype # To find the datatype

dtype('int64')

In [36]:
threeD_array = np.arange(27).reshape(3,3,3)

In [37]:
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


# Numpy - Basic Operations

In [41]:
# addition

np.add(45, 20)

65

In [42]:
#subtraction
np.subtract(20, 10)

10

In [45]:
# ndarray multiplication

no_of_hrs_worked_a_day = [7,3,2,6,4]
salary_per_hr = 100
np_daily_wage = np.array(no_of_hrs_worked_a_day)* salary_per_hr


In [46]:
print(np_daily_wage)

[700 300 200 600 400]


In [47]:
# Total earning of 5 days
sum(np_daily_wage)


2200

## Comparison Operations

In [48]:
np_weekly_hrs = np.array([23, 43, 22, 54, 34])

In [49]:
np_weekly_hrs[np_weekly_hrs > 40]

array([43, 54])

In [50]:
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 43, 22, 54, 34])

## Logical Operations

In [52]:
np.logical_and(np_weekly_hrs>20, np_weekly_hrs<50) 

array([ True,  True,  True, False,  True])

In [53]:
np.logical_not(np_weekly_hrs>35)

array([ True, False,  True, False,  True])

In [55]:
# To find a test score

test_scores = np.array([[83, 45, 50, 71, 90], [98, 55, 46, 73, 80]])

passing_score = test_scores > 60

passing_score

array([[ True, False, False,  True,  True],
       [ True, False, False,  True,  True]])

In [56]:
test_scores[passing_score]

array([83, 71, 90, 98, 73, 80])

## Shape Manipulation

In [57]:
new_arr = np.array([[10, 20, 30, 40, 50], [11, 21, 31, 41, 51]])

In [58]:
new_arr.ravel() # Flatten the array or dataset

array([10, 20, 30, 40, 50, 11, 21, 31, 41, 51])

In [61]:
new_arr.reshape(2,5)

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51]])

In [65]:
new_arr.resize(2,5)

In [66]:
new_arr

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51]])

In [68]:
np.hsplit(new_arr, 5) # Splits the array horizontally

[array([[10],
        [11]]),
 array([[20],
        [21]]),
 array([[30],
        [31]]),
 array([[40],
        [41]]),
 array([[50],
        [51]])]

In [70]:
new_arr_1 = np.array([10, 25, 7, 66, 8, 9])
new_arr_2 = np.array([11, 32, 4, 5, 6, 90])

In [72]:
np.hstack((new_arr_1, new_arr_2)) # Stacks the array together

array([10, 25,  7, 66,  8,  9, 11, 32,  4,  5,  6, 90])